project_id = "erekvlqjibmzrfrzzqam"

[functions.github-webhook]
verify_jwt = false

[functions.gitlab-webhook]
verify_jwt = false

[functions.jenkins-webhook]
verify_jwt = false

[functions.deployment-webhook]
verify_jwt = false
